### ISSUE TITLE
Populating with data

### ISSUE THREAD

**Issue by pandafinity** [LunarLogic/starability#10]
Hi,

Really not sure if this is a 'code' issue (well actually more a usability issue), but I wanted to see how you would set that star rating from a variable?  

So, if I have a variable 'newRating' with the value of 4 how would I set your Starability to reflect this, instead of clicking on the 4th star?

**Comment by szynszyliszys** [comment]
Well (if I understand the question correctly) you would have to set the state of a desired rating to checked. This means you would have to grab the input element that needs to be chosen and set its '.checked' value to true like this: 

document.getElementById('rate4').checked = true;

Does that answer your question, @pandafinity?

**Comment by pandafinity** [comment]
Hello,
Sorry it's taken so long to reply, gmail is full an I had forgotten my password...

```
    for (i = 0; i < starRating.length; ++i) {
      if (starRating[i].value == rating) { starRating[i].checked = true; }
      starRating[i].disabled = true;
    }

```
As I was pulling the star value from a database I used the above..
Thank you for answering though, and sorry again for being so late :)

:)

**Comment by szynszyliszys** [comment]
@pandafinity great that you find your way around it though! :)
