### ISSUE TITLE
How to remove rate selecion

### ISSUE THREAD

**Issue by deleugpn** [LunarLogic/starability#14]
I noticed that after clicking on a star, there's no way for the user to _undo_ a selection. I was wondering how one could achieve this goal to allow users to regret rating at all.

**Comment by szynszyliszys** [comment]
Well the stars are made with checkboxes and by default you cannot uncheck the checkbox, so there is no default way to do that. You can play with javascript and on a second click on selected rating change the value of the "checked" attribute to false.
