### ISSUE TITLE
Remove outline around stars after selection/during keyboard navigation?

### ISSUE THREAD

**Issue by dandv** [LunarLogic/starability#20]
Chrome:

![image](https://user-images.githubusercontent.com/33569/27106591-e4b70cbc-5048-11e7-96f2-779f46592a6e.png)

Firefox:

![image](https://user-images.githubusercontent.com/33569/27106609-f8bc4394-5048-11e7-838e-96971c9ad8be.png)

**Comment by szynszyliszys** [comment]
Hi @dandv, there is a SASS variable to turn this off, the outline is mainly for accessibility reasons there. More explaination is here already: https://github.com/LunarLogic/starability/pull/19

I think I will turn this off by default, as it seems to be confusing for many people.
