### ISSUE TITLE
Is it possible when the case of no checked stars to make that case all unchecked?

### ISSUE THREAD

**Issue by murhafh** [LunarLogic/starability#21]

**Comment by szynszyliszys** [comment]
Hi @murhafh, see if this answers your question: https://github.com/LunarLogic/starability/issues/14

**Comment by murhafh** [comment]
Thanks I managed to do that by setting `background-position: 0 0` in for example `.starability-growRotate>label` and then adding another entry `.starability-growRotate>input:checked+label:before {
opacity: 1
}` 

That seem to do the trick have all stars unchecked by default if no star is checked.

**Comment by iFlash** [comment]
murhafh: That does not completely do the trick. It starts with no stars selected, but when you select, let's 5 stars, and then you want to select ONE stars, the stars 2,3, and 4 while hovering over the first star will not turn grey.

**Comment by szynszyliszys** [comment]
I've added an empty input to have no rating at all at the beginning in the new version. You can copy it from the [README](https://github.com/LunarLogic/starability/blob/master/README.md) or [index.html](https://github.com/LunarLogic/starability/blob/master/index.html).
