### ISSUE TITLE
Rating starts with yellow stars instead of grey stars

### ISSUE THREAD

**Issue by iFlash** [LunarLogic/starability#22]
When I use the newest version of starability, the stars appear yellow (as if a 5-star rating already had been given), although NONE of the radio buttons has is "checked". 

This is misleading the user. The rating should be shown in grey initially.

The solution in #21 does not do the trick entirely as it breaks the proper coloring of the stars after an initial rating has been set, for example: Check 5 stars, then check one star. While hovering over the first star, the other stars stay yellow.

**Comment by szynszyliszys** [comment]
Hi @iFlash, I have one day break in holiday and I will try to look at this today. I hope that I will find a solution for you today, if not I will look at it further next week. In the meantime you can find the source code for the older version of the library here, it used to work there: https://github.com/LunarLogic/starability/releases/tag/v1.3.2

**Comment by szynszyliszys** [comment]
Hey @iFlash I've added an empty input to have no rating at all at the beginning in the new version. You can copy it from the [README](https://github.com/LunarLogic/starability/blob/master/README.md) or [index.html](https://github.com/LunarLogic/starability/blob/master/index.html).

**Comment by iFlash** [comment]
Works like a charm – thanks!

**Comment by szynszyliszys** [comment]
Glad to hear that, @iFlash <3

**Comment by iFlash** [comment]
Here you can see how it looks like:

https://www.retroplace.com/en/games/collection/Armin

(The webpage is still in development – a marketplace for retro video and computer games)

**Comment by amcaplan** [comment]
This fix solves the display problem, but unfortunately it means there's no way to simply make a star rating `required` with HTML5. As far as the browser is concerned, `value="0"` is still a valid value, so hitting `Submit` works fine.  Even if semantically I treat it on the server side as though it was left out, that means a full client=>server=>client roundtrip to validate required fields.
