### ISSUE TITLE
Touch gesture support

### ISSUE THREAD

**Issue by Blankarsch** [LunarLogic/starability#24]
Great work! A pan-gesture support for touchscreens would it make even more awesome ;)

**Comment by szynszyliszys** [comment]
Hm, could look at it tomorrow @Blankarsch. If touch-action property will do nicely I can add that. If not - I don't want to make the code any heavier by adding JS.

**Comment by MaximilianSchieder** [comment]
Something like this? [Touch Action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)

**Comment by szynszyliszys** [comment]
@Blankarsch @MaximilianSchieder I just checked and it doesn't seem it can be done easily with touch-action property since we are using checkboxes here (tried on a fieldset and form and didn't work).

I will drop this idea for now then, as I don't want to add unnecessary scripts here.
