### ISSUE TITLE
Star size

### ISSUE THREAD

**Issue by valecarlos** [LunarLogic/starability#27]
What's the best way to change the star size? I've changed the $star-size in _variables.scss but i get an unexpected output, I'm guessing that it's because the star base64 image has set dimensions and to display the star it's actually using the image as a background image?

How should I go about resizing the stars? Thanks!

**Comment by szynszyliszys** [comment]
Hi @valecarlos you are right about why it behaves this way. To resize the stars you would have to change the value of the variable `$star-size` and also create your own background image in needed size and add it as base64 or regular background image. This option probably will never be supported by default, but you can create your own fork with stars of a different size and share it. :)

**Comment by valecarlos** [comment]
Thanks! I was kind of in a rush to get this going so here's what I did, in case anyone else needs it:
1. Using the code from this [SO answer](https://stackoverflow.com/questions/33291436/can-you-resize-or-change-resolution-of-base64-image-through-manipulating-the-bas#) I resized the image dimensions.
You can see my modified version in [this fiddle](https://jsfiddle.net/hyx30w2m/)

2. Then I right clicked on the new image and saved it, so I could upload it into an online base64 encoder.

3. Copied the encoded version in `$img-stars-sprite` changed the `$star-size` and ran the gulp task.

And got it working as expected, thanks for your help and the quick reply! @szynszyliszys

**Comment by szynszyliszys** [comment]
Great, I am glad that you've found a solution! I hope everything will work as expected. :)
