### ISSUE TITLE
Focus ring is not demonstrated in example HTML

### ISSUE THREAD

**Issue by mislav** [LunarLogic/starability#30]
The README states “It is not advised though to remove the outline.” However, the `.starability-focus-ring` element isn't shown in the example HTML for the rating widget.

Furthermore, the focus ring CSS depends on an element with ID `#no-rate`. If there are multiple rating widgets on the page, they would all need to share the same element ID for this to work. This might not be a huge problem, but it might trigger duplicate ID detection mechanisms in some apps. Consider switching to a class name instead.

**Comment by szynszyliszys** [comment]
@mislav thank you for the remark, accessibility focus ring is there and it is not hooked to id. :)
