### ISSUE TITLE
Better support for `disabled` attribute.

### ISSUE THREAD

**Issue by ciembor** [LunarLogic/starability#31]
Value of disabled input cannot be changed, that is good. Yet the stars on hover have the same color as when it's active. Hovering disabled input shouldn't change color to yellow. This can be easily achieved:

```
  @if ($hover-enabled) {
    > input:hover:not(:disabled) ~ label {
      background-position: 0 (-$star-size);
    }
  }
```

## edit

Another thing - the coursor shouldn't be set to `pointer` in such case.

```
  > input:disabled+label {
    cursor: not-allowed;
    // or default
  }
```

**Comment by ciembor** [comment]
@szynszyliszys Do you want a PR with this, or is it a `#wontfix` issue and I shouldn't bother? Maybe I shouldn't use `disabled` attribute for some reason, and I should use `starability-result` class instead? If yes, what is the reason?

**Comment by szynszyliszys** [comment]
@ciembor If you did a PR with that I would review and merge if that looks fine. Sorry, I was pretty busy recently. 

I would set cursor to `default`.

**Comment by szynszyliszys** [comment]
@ciembor I fixed that, now there is no highlight on hover and the default cursor when stars are disabled.
