### ISSUE TITLE
Stars invisible in high contrast mode

### ISSUE THREAD

**Issue by scottaohara** [LunarLogic/starability#32]
Hi again.

I was checking starability, since it's been awhile, and noticed that if a user has high contrast mode enabled, that all of the stars vanish, due to them being background images.

Thinking of solutions for this, I've gotten around this issue by using SVGs in place of background images, though I realize that'd be quite a bit of work, and could make some of the animations difficult.

That said, being in high contrast mode, design isn't nearly as critical, as much as it's about having a usable interface. With that in mind, an alternative could be to have a high contrast mode media query where the UI changed from &star; `&star;` vs &#9733; `&#9733;` to indicated a selected vs non-selected rating.

While typically I wouldn't want to use those sorts of characters in CSS content, to mitigate the possibility of screen readers reading out "black star" and such, I'd consider it a minor annoyance for the individuals who are using both a screen reader & high contrast mode. And it would far outweigh the annoyance of having invisible UI.

Let me know if you have any questions about this that I didn't cover. 

Thanks :)

**Comment by szynszyliszys** [comment]
Hi @scottaohara I just took a look at that and I believe that it is impossible to replace the background with a unicode character in the current setup: starability is using image sprites for that and a pretty neat hack to enable hovering the stars. Rewriting it with svg could indeed break some of the animations.

How about we remove the styling in case someone is using a high contrast mode? Then these are just regular radio buttons that are accessible?

![screen shot 2018-08-08 at 16 14 16](https://user-images.githubusercontent.com/1983291/43842658-219d7700-9b26-11e8-8215-872d557494c0.png)

**Comment by scottaohara** [comment]
Yeh, that makes sense.  I had to fiddle with it quite a bit to get the stars to show up with CSS content. 

But yeh, I think just falling back to regular radio buttons is a great idea.  :)

**Comment by scottaohara** [comment]
Gave the branch a quick test on my PC and the radio buttons are visible.  

Right now high contrast mode is a windows thing that IE, Edge, and mostly-firefox support.

Apple has things like inverted colors and such, but that doesn't remove background images like high contrast mode does.  So this should be a-ok for macs still.

**Comment by szynszyliszys** [comment]
@scottaohara thank you! Will merge it then :)
