### ISSUE TITLE
Regarding stability star 10 rating

### ISSUE THREAD

**Issue by dilshanzuhdi** [LunarLogic/starability#34]

**Comment by dilshanzuhdi** [comment]
can you please help me to get 10 star rating

**Comment by kegan09** [comment]
> can you please help me to get 10 star rating

Look at the HTML example on the main page, copy and paste the 1-5 star code and change 1-5 to 6-10. No extra functionality should be needed, just a little more HTML.

**Comment by szynszyliszys** [comment]
Hey @dilshanzuhdi, to do so you need to add 10 fields instead of 5 (the tutorial in readme shows 5 files) and adjust the scss file to have variable `$star-count` set to 10 instead of 5 here: https://github.com/LunarLogic/starability/blob/master/starability-scss/_variables.scss#L1
