### ISSUE TITLE
Node throws SyntaxError: Unexpected token '.' for npm package css

### ISSUE THREAD

**Issue by rmgreenstreet** [LunarLogic/starability#36]
I've installed starability and required it in my app.js file, and when I try to run the app, it breaks with this syntax error:

```
node_modules\starability\starability-css\starability-all.css:1
.starability-result {
^

SyntaxError: Unexpected token '.'
```

Dunno if this is specific to this package, or if Node itself is reading it wrong. I've looked at the file and it looks fine to me.

When I remove the `require` statement for starability, the app starts just fine.

**Comment by szynszyliszys** [comment]
Hey @rmgreenstreet, I am sorry for late reply. I have not had chance to use Node as my dev environment, but maybe you are missing a CSS loader in your project? Have you tried importing the starability css files from node_modules directly in your stylesheets?
