### ISSUE TITLE
Change size of stars?

### ISSUE THREAD

**Issue by produktive** [LunarLogic/starability#37]
Is there a way to change the size of the stars? I would like to make them bigger and changing height and width properties in the HTML has no effect.

**Comment by szynszyliszys** [comment]
Hey @produktive, there is a variable for changing the star sizes (if you are using scss version): https://github.com/LunarLogic/starability/blob/master/starability-scss/_variables.scss#L2

**Comment by eneda8** [comment]
this doesn't work...
