### ISSUE TITLE
Dosn't work in 2021?

### ISSUE THREAD

**Issue by Tastaturberuf** [LunarLogic/starability#41]
no animations are fired in the demo. Does anyone have a solution?

**Comment by szynszyliszys** [comment]
What browser are you using? I just checked in Firefox and Chrome and it works. Check thrid animation type and onward to see the effect.

**Comment by Tastaturberuf** [comment]
Latest Chrome 92.0.4515.107
Latest Firefox Developer Version

Only the default animation works on all except the slot variant but that look little bit clunky.

**Comment by Tastaturberuf** [comment]
Oh damn, i think there where other hover animations like the slot version. but ist on click...

![image](https://user-images.githubusercontent.com/1027521/127287814-b8c79721-3f85-44bb-a50d-c0a553e6aba6.png)

Sorry my bad.
