### ISSUE TITLE
Sub-star ratings

### ISSUE THREAD

**Issue by jakiestfu** [LunarLogic/starability#9]
Hello. Over at [DSC](https://www.dollarshaveclub.com/our-products/shave/shave-butter), we use our own setup for star ratings.

I applaud you for devising an accessible solution to this issue. Is sub-star rating a possiblity? i.e. 4.7/5? We've come up with some crafty solutions but I fear they are not as accessible as this.

**Comment by szynszyliszys** [comment]
Hi @jakiestfu, thank you for your feedback! As for 4.7/5 rating - it would require having a system that let's user rate every 0.1 point of a star and it would be both hard to implement (we need a new input/label for every one of them 0.1 point, which means 10 times more markup than we have now) and also probably hard to use for people who are on mobile version of a website or have motor disabilities. What is more, it would make the rating system hard to use for a person using a screen reader, as he or she would have to listen to so many more options before for example accessing a 3rd star option. Therefore, making such detailed rating is hard to create in any context and I am not willing to go with this option in case of Starability. The most I could agree on is rating every 0.5 star, but I am still not convinced if it is necessary and justified here.

**Comment by dandv** [comment]
@jakiestfu: I've documented several half-star and fractional-star widgets in my [Comparison of star-rating widgets](https://github.com/dandv/comparisons/blob/master/star-rating-widgets.md#superset-of-features).
